### ISSUE TITLE
Questions about some bikes

### ISSUE THREAD

**Issue by GH0st3rs** [int-0x03/masksorter#1]
# Duplicate code
https://github.com/int-0x03/masksorter/blob/83f63560362f5df673cd8de81e88bea716ffb2c9/masksorter.py#L32
```python
cnt = mask.count(mask_char)
if cnt > 0:
...
```

# Difficult calculations
https://github.com/int-0x03/masksorter/blob/83f63560362f5df673cd8de81e88bea716ffb2c9/masksorter.py#L68
```python
return len(mask)//2
```

# Maybe need replace to Argparse functions
https://github.com/int-0x03/masksorter/blob/83f63560362f5df673cd8de81e88bea716ffb2c9/masksorter.py#L72

# Extra conversion
https://github.com/int-0x03/masksorter/blob/83f63560362f5df673cd8de81e88bea716ffb2c9/masksorter.py#L42
```python
return range(startR, endR)
```

# Pylint Error
```bash
% pylint masksorter.py 
************* Module masksorter
masksorter.py:77:18: C0326: Exactly one space required around assignment
        difficulty=calculate_difficult(line)
                  ^ (bad-whitespace)
masksorter.py:81:28: C0326: Exactly one space required around assignment
            total_difficulty+=difficulty
                            ^^ (bad-whitespace)
masksorter.py:91:0: W0311: Bad indentation. Found 12 spaces, expected 8 (bad-indentation)
masksorter.py:4:0: W1401: Anomalous backslash in string: '\]'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
masksorter.py:15:-1: W0105: String statement has no effect (pointless-string-statement)

-----------------------------------
Your code has been rated at 9.14/10
```

**Comment by int-0x03** [comment]
Difficult calculations: `return len(mask)//2` does not work properly.
All other points have been corrected.
